language: node_js
node_js:
  - "10"
services:
  - postgresql
before_script:
  - psql -c 'create database MyDiary_test;' -U postgres
branches:
  only:
    - develop
script: 
  - npm install
script:
  - npm test
after_success:
  - npm run coveralls
